# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensorsetting.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SensorSetting(object):
    def setupUi(self, SensorSetting):
        SensorSetting.setObjectName(_fromUtf8("SensorSetting"))
        SensorSetting.resize(600, 400)
        self.tabWidget = QtGui.QTabWidget(SensorSetting)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 570, 320))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 521, 251))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox.setChecked(True)
        self.horizontalLayout.addWidget(self.checkBox)
        self.horizontalSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider.setRange(0, 200)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider.setEnabled(True)
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_2 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_2.setChecked(True)
        self.horizontalLayout_4.addWidget(self.checkBox_2)
        self.horizontalSlider_2 = QtGui.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.horizontalSlider_2.setRange(0, 200)
        self.horizontalSlider_2.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_2.setEnabled(True)
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_3 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_3.setChecked(True)
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.horizontalSlider_3 = QtGui.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.horizontalSlider_3.setRange(0, 200)
        self.horizontalSlider_3.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_3.setEnabled(True)
        self.horizontalLayout_3.addWidget(self.horizontalSlider_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setMargin(11)
        self.horizontalLayout_18.setSpacing(20)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setMargin(11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_20.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_20.addWidget(self.lineEdit)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setMargin(11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_21.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_21.addWidget(self.lineEdit_2)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setMargin(11)
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_23.addWidget(self.label_4)
        self.lineEdit_4 = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.horizontalLayout_23.addWidget(self.lineEdit_4)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_23)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(19, 19, 521, 251))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBox_4 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_4.setChecked(True)
        self.horizontalLayout_5.addWidget(self.checkBox_4)
        self.horizontalSlider_4 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.horizontalSlider_4.setRange(0, 200)
        self.horizontalSlider_4.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_4.setEnabled(True)
        self.horizontalLayout_5.addWidget(self.horizontalSlider_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_5 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_5.setChecked(True)
        self.horizontalLayout_7.addWidget(self.checkBox_5)
        self.horizontalSlider_5 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName(_fromUtf8("horizontalSlider_5"))
        self.horizontalSlider_5.setRange(0, 200)
        self.horizontalSlider_5.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_5.setEnabled(True)
        self.horizontalLayout_7.addWidget(self.horizontalSlider_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox_6 = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_6.setChecked(True)
        self.horizontalLayout_6.addWidget(self.checkBox_6)
        self.horizontalSlider_6 = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName(_fromUtf8("horizontalSlider_6"))
        self.horizontalSlider_6.setRange(0, 200)
        self.horizontalSlider_6.setTickPosition(QtGui.QSlider.TicksAbove)
        self.horizontalSlider_6.setEnabled(True)
        self.horizontalLayout_6.addWidget(self.horizontalSlider_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setMargin(11)
        self.horizontalLayout_19.setSpacing(20)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setMargin(11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_24.addWidget(self.label_5)
        self.lineEdit_5 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.horizontalLayout_24.addWidget(self.lineEdit_5)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setMargin(11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_25.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_25.addWidget(self.lineEdit_6)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setMargin(11)
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_26.addWidget(self.label_7)
        self.lineEdit_7 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_26.addWidget(self.lineEdit_7)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(SensorSetting)
        self.pushButton.setGeometry(QtCore.QRect(480, 350, 90, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(SensorSetting)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SensorSetting)

    def retranslateUi(self, SensorSetting):
        SensorSetting.setWindowTitle(_translate("SensorSetting", "SensorSetting", None))
        self.checkBox.setText(_translate("SensorSetting", "x:", None))
        self.checkBox_2.setText(_translate("SensorSetting", "y:", None))
        self.checkBox_3.setText(_translate("SensorSetting", "z:", None))
        self.label.setText(_translate("SensorSetting", "acc_x:", None))
        self.label_2.setText(_translate("SensorSetting", "acc_y:", None))
        self.label_4.setText(_translate("SensorSetting", "acc_z:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SensorSetting", "Sensor 1", None))
        self.checkBox_4.setText(_translate("SensorSetting", "x:", None))
        self.checkBox_5.setText(_translate("SensorSetting", "y:", None))
        self.checkBox_6.setText(_translate("SensorSetting", "z:", None))
        self.label_5.setText(_translate("SensorSetting", "acc_x:", None))
        self.label_6.setText(_translate("SensorSetting", "acc_y:", None))
        self.label_7.setText(_translate("SensorSetting", "acc_z:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SensorSetting", "Sensor 2", None))
        self.pushButton.setText(_translate("SensorSetting", "OK", None))

